version: "3.3"
services:
    zookeeper:
      image: wurstmeister/zookeeper:latest
      ports:
        - "2181:2181"
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
      image: wurstmeister/kafka:2.13-2.8.1
      ports:
        - "9092:9092"
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_LISTENERS=PLAINTEXT://:9092
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.22.208.1:9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zookeeper
    spark:
      image: jupyter/all-spark-notebook:spark-3.1.1
      ports:
        - "8888:8888"
        - "4040-4080:4040-4080"
      links:
        - "kafka:kafka-server" 
      volumes:
        - ../notebooks:/home/jovyan/work/notebooks/
